### ISSUE TITLE
ModuleNotFoundError: No module named 'neck'

### ISSUE THREAD

**Issue by harindermashiana** [zllrunning/SiameseX.PyTorch#6]
Whenever I try to run the demo code, I receive the following error:
```
Traceback (most recent call last):
  File "demo.py", line 10, in <module>
    from demo_utils.siamvggtracker import SiamVGGTracker
  File "C:\Users\Harinder\Desktop\SiameseX.PyTorch\demo_utils\siamvggtracker.py", line 12, in <module>
    from demo_utils.siamese import SiameseNet
  File "C:\Users\Harinder\Desktop\SiameseX.PyTorch\demo_utils\siamese.py", line 16, in <module>
    import models.builder as builder
  File "C:\Users\Harinder\Desktop\SiameseX.PyTorch\models\builder.py", line 10, in <module>
    from neck import AdjustLayer, AdjustAllLayer
ModuleNotFoundError: No module named 'neck'
```

**Comment by harindermashiana** [comment]
You need to write .neck instead of neck while importing neck in builder.py file

**Comment by hans-bbt** [comment]
can you explain more in detail
